# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-20 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseCode', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('LIC_name', models.CharField(max_length=50)),
                ('LIC_email', models.CharField(max_length=100)),
                ('LIC_phone', models.IntegerField(max_length=11)),
            ],
        ),
    ]
