# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-25 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20160820_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='LIC_email',
            field=models.CharField(max_length=100, verbose_name='LIC Email'),
        ),
        migrations.AlterField(
            model_name='course',
            name='LIC_name',
            field=models.CharField(max_length=50, verbose_name='Lecturer in Charge'),
        ),
        migrations.AlterField(
            model_name='course',
            name='LIC_phone',
            field=models.IntegerField(verbose_name='LIC Phone'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseCode',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
    ]
