# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apptType',
            fields=[
                ('apptType', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('apptDesc', models.CharField(max_length=450)),
            ],
        ),
    ]
