# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-20 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('zID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('stu_email', models.CharField(max_length=100)),
            ],
        ),
    ]
