# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20160820_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(default='Bachelor of Information Systems', max_length=100),
            preserve_default=False,
        ),
    ]
