# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20160921_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='degree',
            fields=[
                ('degreeCode', models.IntegerField(primary_key=True, serialize=False, verbose_name='Degree Code')),
                ('degreeName', models.CharField(max_length=200, verbose_name='Degree')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
    ]
