# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_degreecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degreeCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.degree', verbose_name='Degree Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='zID'),
        ),
    ]
