# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20161006_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrol',
            old_name='course_old',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='enrol',
            name='course_new',
        ),
        migrations.AddField(
            model_name='enrol',
            name='grade',
            field=models.IntegerField(null=True, verbose_name='Grade'),
        ),
    ]
