# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20161019_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrol',
            name='sem_taken',
            field=models.CharField(max_length=20, null=True, verbose_name='Semester/Year Taken'),
        ),
    ]
