# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-22 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_enrol_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrol',
            name='sem_taken',
            field=models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2')], max_length=20, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='year',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2016, verbose_name='year'),
        ),
    ]
