# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20161022_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrol',
            name='WAM',
            field=models.IntegerField(default=50, verbose_name='Term WAM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrol',
            name='year',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2016, verbose_name='year'),
        ),
    ]
