# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-23 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_coopplacement_placementcompanies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementcompanies',
            name='id',
        ),
        migrations.AlterField(
            model_name='placementcompanies',
            name='company',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Company'),
        ),
    ]
