# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20161024_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopplacement',
            name='secondPref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecondPreference', to='student.placementCompanies', verbose_name='Second Preference'),
        ),
        migrations.AlterField(
            model_name='coopplacement',
            name='thirdPref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ThirdPreference', to='student.placementCompanies', verbose_name='Third Preference'),
        ),
    ]
