# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20161024_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopplacement',
            name='zID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='zID'),
        ),
    ]
