# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-25 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20161024_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrol',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', unique=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='year',
            field=models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2016, verbose_name='Year'),
        ),
    ]
