# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bootstrap_calendar', '0003_auto_20160908_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
