# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-08 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bootstrap_calendar', '0004_auto_20160908_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='url',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='URL'),
        ),
    ]
