# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-18 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bootstrap_calendar', '0005_auto_20160908_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='id',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notes',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='ugc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='css_class',
            field=models.CharField(blank=True, choices=[(b'', 'Normal'), (b'event-warning', 'Warning'), (b'event-info', 'Info'), (b'event-success', 'Success'), (b'event-inverse', 'Inverse'), (b'event-special', 'Special'), (b'event-important', 'Important')], max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Title'),
        ),
    ]
