# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bootstrap_calendar', '0006_auto_20160918_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
