# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptType', '0001_initial'),
        ('django_bootstrap_calendar', '0008_consulttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='apptType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apptType.apptType'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time & Date'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start',
            field=models.DateTimeField(verbose_name='Start Time & Date'),
        ),
    ]
