# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_bootstrap_calendar', '0009_auto_20160921_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='apptType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apptType.apptType', verbose_name='Appointment Type'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='notes',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='ugc',
            field=models.CharField(max_length=100, null=True, verbose_name='Staff'),
        ),
    ]
