# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bootstrap_calendar', '0010_auto_20160926_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='css_class',
            field=models.CharField(choices=[(b'event-success', 'Low'), (b'event-warning', 'Medium'), (b'event-important', 'High')], default=b'event-success', max_length=20, null=True, verbose_name='Priority'),
        ),
    ]
