# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bootstrap_calendar', '0012_auto_20161024_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date & Time'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start',
            field=models.DateTimeField(verbose_name='Start Date & Time'),
        ),
    ]
