# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_auto_20160820_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sTime', models.DateTimeField()),
                ('fTime', models.DateTimeField()),
                ('priority', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=400)),
                ('zID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
