# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='cID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
