# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptType', '0001_initial'),
        ('consultation', '0004_remove_consultation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptType.apptType')),
                ('cID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation')),
            ],
        ),
    ]
