# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consulttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='priority',
            field=models.IntegerField(default=False),
        ),
    ]
