# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-31 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_auto_20160824_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='hgc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
