# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-31 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_consultation_hgc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='hgc',
            new_name='ugc',
        ),
    ]
