# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_auto_20160831_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulttype',
            name='apptType',
        ),
        migrations.RemoveField(
            model_name='consulttype',
            name='cID',
        ),
        migrations.DeleteModel(
            name='consultType',
        ),
    ]
